version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "covenants-fake-ocr"
s3_bucket = "covenants-deed-images"
s3_prefix = "covenants-fake-ocr"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
